# -*- coding: utf-8 -*-
"""NM - Heart risk chatbot .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n0_WBYBFn2zSQJQGbbE2NXR_VNtclb-2
"""

!pip install -q google-generativeai
# Import necessary libraries
import google.generativeai as genai
import IPython.display as display
import getpass
genai.configure(api_key="AIzaSyDkKQC09sgWXpj35cCfjrAKZD0Z-YSKCrU")
model = genai.GenerativeModel("gemini-1.5-pro-latest")
chat = model.start_chat(history=[])
model = genai.GenerativeModel(
    model_name="gemini-1.5-pro-latest",
    system_instruction="""
    You are a helpful and knowledgeable AI assistant that answers questions about heart disease and related risks.
    Provide clear, accurate, and concise medical information based on current research.
    Avoid giving personal medical advice—recommend consulting a doctor when necessary.
    """
)

chat = model.start_chat(history=[])
def ask_medical_bot():
    print("💬 Heart Risk Q&A Chatbot (type 'exit' to quit)\n")
    while True:
        user_input = input("You: ")
        if user_input.lower() in ["exit", "quit", "bye"]:
            print("Bot: Take care! Stay heart healthy. ❤️")
            break
        try:
            response = chat.send_message(user_input)
            print("Bot:", response.text, "\n")
        except Exception as e:
            print("Bot: Sorry, there was an error processing your question.")
            print("Error:", str(e), "\n")
# Start the chat
ask_medical_bot()