# -*- coding: utf-8 -*-
"""Streamlit app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1So3cpQaaMXxJ5faJZj63uJLae3X3d46s
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile heart_chatbot_app.py
# import streamlit as st
# import google.generativeai as genai
# 
# # Set up Gemini API key
# API_KEY = st.secrets["GEMINI_API_KEY"]
# genai.configure(api_key=API_KEY)
# 
# # Load Gemini 1.5 Pro with system prompt
# model = genai.GenerativeModel(
#     model_name="gemini-1.5-pro-latest",
#     system_instruction="""
#     You are a helpful and knowledgeable AI assistant that answers questions about heart disease and related risks.
#     Provide clear, accurate, and concise medical information based on current research.
#     Avoid giving personal medical advice—recommend consulting a doctor when necessary.
#     """
# )
# 
# # Start chat session
# if "chat" not in st.session_state:
#     st.session_state.chat = model.start_chat(history=[])
# 
# st.title("❤️ Heart Risk Q&A Chatbot")
# st.write("Ask any question about heart disease, symptoms, or prevention tips.")
# 
# user_input = st.text_input("You:", key="input")
# 
# if user_input:
#     st.session_state.chat.send_message(user_input)
#     response = st.session_state.chat.last.text.strip()
#     st.markdown(f"**Bot:** {response}")
# 
# # Display chat history
# if st.button("Show Full Chat History"):
#     st.markdown("### Chat History:")
#     for turn in st.session_state.chat.history:
#         st.markdown(f"**You:** {turn.parts[0].text}")
#         st.markdown(f"**Bot:** {turn.parts[1].text}")
#


